In [1]:
import yfinance as yf
import datetime
from datetime import timedelta
from os.path import exists
import pandas as pd

class YahooData:
    def __init__(self, startDate, endDate):
        self.startDate = startDate
        self.endDate = endDate

    def getYahooData(self, keyword):
        historical_data = yf.download(keyword, start=self.startDate, end=self.endDate, progress=False)
        #historical_data = yahoo.get_historical(self.startDate, self.endDate)
        return historical_data
    
file_exists = exists('../Data/yahoo_data.dat')

if file_exists is False:
    historical_data = YahooData('1999-01-04','2011-04-29').getYahooData('EURUSD=X')
    historical_data.to_pickle('../Data/yahoo_data.dat')
else:
    print('Reading existing file...')
    historical_data = pd.read_pickle('../Data/yahoo_data.dat')

Reading existing file...

In [2]:
historical_data

                Open      High       Low     Close  Adj Close  Volume
Date
2003-12-01  1.203398  1.204007  1.194401  1.196501   1.196501       0
2003-12-02  1.196101  1.210903  1.194600  1.208897   1.208897       0
2003-12-03  1.209000  1.213003  1.207700  1.212298   1.212298       0
2003-12-04  1.212004  1.214403  1.204398  1.208094   1.208094       0
2003-12-05  1.207802  1.219096  1.206593  1.218695   1.218695       0
...              ...       ...       ...       ...        ...     ...
2011-04-25  1.455519  1.462566  1.453045  1.455710   1.455710       0
2011-04-26  1.457790  1.464901  1.449969  1.457896   1.457896       0
2011-04-27  1.468990  1.470999  1.463807  1.468795   1.468795       0
2011-04-28  1.478000  1.488206  1.477847  1.478000   1.478000       0
2011-04-29  1.484296  1.487896  1.480494  1.484406   1.484406       0

[1911 rows x 6 columns]

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

yahoo_variables = historical_data.to_numpy()[:,[0,1,2]]
yahoo_close_price = historical_data.to_numpy()[:,3]

x_train, x_test, y_train, y_test = train_test_split(yahoo_variables, yahoo_close_price, train_size=0.80, shuffle=False)

sc_x = MinMaxScaler(feature_range=(0,1))
sc_y = MinMaxScaler(feature_range=(0,1))

x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

y_train = sc_y.fit_transform(y_train.reshape(-1, 1))

In [ ]:
# usando data real
time_start = time.time()

maxi_iter=50
#pN: número de partículos
#dim: dimensión de búsqueda
pso = PSO(pN=15, dim=9, max_iter=maxi_iter,data=x_train,Y=y_train)
pso.init_Population()
fitness = pso.iterator()
time_end = time.time()
print('Time：', time_end - time_start)

bestRbf=pso.layoutBest()
trainoutcome2=bestRbf.test(np.array(x_train))
print()
print('resultados de entrenamiento：')

testOutcome=bestRbf.test(np.array(x_test))
print('Resultados de la muestra de prueba：')

In [ ]:
prediction = sc_y.inverse_transform(testOutcome)

dates = historical_data.index

plt.figure(figsize=(16,8))
#Real values
plt.plot(dates[-y_test.size:], y_test, label='Original ')#sc_y.inverse_transform(y_test)
#Predicted values
plt.plot(dates[-y_test.size:], prediction, label='Pred ')
#Legend location
plt.legend(loc = 'best')
    
plt.show()